title: "Conform: Web標準をもとに Remix / Nextjs app router に対応する型安全フォームバリデーションライブラリ"
summary: "Conform は、Web 標準に基づいて HTML フォームを段階的に強化し、RemixやNext.jsのようなサーバーフレームワークを完全にサポートする、型安全なフォームバリデーションライブラリです。\n\nhttps://conform.guide"
topics: ["Conform", "Remix", "Nextjs", "React"]
published: false
price: 0
chapters:
  - tutorial
  - overview
  - upgrading-v1
  - validation
  - complex-structures
  - intent-button
  - checkbox-and-radio-group
  - file-upload
  - accessibility
  - integration_ui-libraries
  - integration_remix
  - integration_nextjs
  - api_react_useForm
  - api_react_useField
  - api_react_useFormMetadata
  - api_react_useInputControl
  - api_react_FormProvider
  - api_react_FormStateInput
  - api_react_getFormProps
  - api_react_getFieldsetProps
  - api_react_getInputProps
  - api_react_getSelectProps
  - api_react_getTextareaProps
  - api_react_getCollectionProps
  - api_yup_parseWithYup
  - api_yup_getYupConstraint
  - api_zod_parseWithZod
  - api_zod_getZodConstraint
  - api_zod_conformZodMessage
